# use vim to move around the terminal
set -o vi

# Alias definitions
if [ -f $OMARA_PATH/configs/bash/aliases ]; then
  . $OMARA_PATH/configs/bash/aliases
fi

# Function definitions
if [ -f $OMARA_PATH/configs/bash/functions ]; then
  . $OMARA_PATH/configs/bash/functions
fi

# Prompt
if [ -f $OMARA_PATH/configs/bash/prompt ]; then
  . $OMARA_PATH/configs/bash/prompt
fi

export EDITOR="nvim"
export SUDO_EDITOR="$EDITOR"

# Command history
HISTFILE="$HOME/.bash_history"
PROMPT_COMMAND="history -a"
HISTCONTROL=ignoreboth:erasedups

shopt -s histappend

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
shopt -s globstar

# allows you to cd into directory by only specifying the directory name
# OUTCOMMENTED becaused it doesnt work with cdspell
#shopt -s autocd

# fix spelling errors in directory names using cd command
shopt -s cdspell

if command -v mise &>/dev/null; then
  eval "$(mise activate bash)"
fi
